apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBaWgcgIzK86LBPosQYbCSWkyydKnLfBREaTN4OlVV0HVFWQ4dO8Dn9hFHc/g0GaP1Y/uBMynT9XXMXDjQnbIkCPWlixFvtVIawWdePE8w5O47olkjPw+8w43cLXEcZkhQwhqcBQNLBj182VSl7ch7PQUHEfOk0fppCfbpVUccgTye2/MnrtaEDYliijwRQCv2koJZOZVe2qj2YWZlxYYIvLyegpDm0a+xECUzVJh/xjiG0IinmlTkQf06cgpuu0qhZG+xB7ravESDHy+CK4y6cCH4MFvJNY3kw5kSSY5PKWnWRMbSQimTYtuc18raVMwDuixl08xaSwFv4LCWS24ajwQgGckUwCFjMKmwmgXDzm4zBOMcfT3RaQVYqssqSYngBbZDuC/nLnPs2fRHj8frtu2L4k7GeFP7iKx7tPz77zmQLZdLDj8wUe+2lXXPlU2swYECJLaf2c7pAVlOAJyGE1Rj9VBbKoGKpsRieKF7cM2d9tKJOF9cjVHDdHyeAgY81DMNj4da4NfUC1iYl1e0wkwmC1SUI5X2IE3mJoL2kH3bOGAvHoSzGf7SF9VbOgtyvLpC9vbz1kX1hZyJkPF40Qt8YmP0Z6LllYck8re1N+dc9u9fMwR1tobEV3pKvKkd1LkGo753jlBHKl9TjSf6UOfyLYcO/GLuGdRUeybZpPgjcjDFgh58oBM8GEl2Ynk4twS01NQQgl/jXkUsgP/aqCGiElg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
